steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:latest'
      - '.'


  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:latest'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - '$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:latest'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

images:
  - '$_ARTIFACT_REGISTRY_REPO/$_SERVICE_NAME:latest'

substitutions:
  _ARTIFACT_REGISTRY_REPO: 'us-central1-docker.pkg.dev/${PROJECT_ID}/mcp-repo'
  _SERVICE_NAME: 'system-crypto-mcp-server'
  _DEPLOY_REGION: 'us-central1'


options:
  logging: CLOUD_LOGGING_ONLY
